name: notedown
description: Notedown

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

module:
  androidX: true

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  scoped_model: ^1.0.1
  # dependency injection
  get_it: ^1.0.3
  http: ^0.12.0+2
  outline_material_icons: ^0.1.1
  flutter_staggered_grid_view: ^0.3.0
  pull_to_refresh: ^1.5.7
  uuid: ^2.0.4
  firebase_auth: ^0.15.0+1
  google_sign_in: ^4.0.14
  cloud_functions: ^0.4.1+4
  fluttertoast: ^3.1.3
  keyboard_visibility: ^0.5.6
  async: ^2.3.0
  markdown: ^2.1.3
  #  flutter_html_view: ^0.5.12
  flutter_html: ^0.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
